### ISSUE TITLE
Custom LLM Model

### ISSUE THREAD

**Issue by Namec999** [Dataherald/dataherald#259] opened 2023-11-21 08:06 UTC
Hello All,

trying to use Dataherald with mistral LLM or with the new SQLCoder

does any one achieved this before, and post some step by step guide to use custom llm models.

best

**Comment by MohammadrezaPourreza** [comment] 2023-11-28 14:18
@Namec999 Hi, I'm working on the open-source LLMs integration with Dataherald, I will write a step by step guide as soon as I can. The issue is that most of open-source LLMs are not good at function calling, so we resort to GPT family.

**Comment by Namec999** [comment] 2023-11-28 14:58
thank you, that will be greate

i am also trying nexusraven open source llm that outperforms the GPT family in function calling

**Comment by alifzl** [comment] 2023-12-05 13:45
Dear @MohammadrezaPourreza , is there any chance that we utilize custom llama-based LLMs in dataherald? consider using a PEFT models like nexusraven with larger parameter size.

**Comment by deeteeakl** [comment] 2023-12-31 18:21
> @Namec999 Hi, I'm working on the open-source LLMs integration with Dataherald, I will write a step by step guide as soon as I can. The issue is that most of open-source LLMs are not good at function calling, so we resort to GPT family.

What about ability to work with Azure OpenAI?  Is that an option?

**Comment by ankur198** [comment] 2023-12-31 19:12
I have attempted to do it. Please have a look it https://youtu.be/ksafgK-S_ko?si=wdx-5Ov4dHYSE6N0

**Comment by MohammadrezaPourreza** [comment] 2024-02-02 15:30
@alifzl @ankur198 @deeteeakl @Namec999 I'm sorry for the delay in getting back to you, but I have some exciting news to share! We now support open-source LLMs, and you can easily use any model from Hugging Face with our tool. We've merged the code, and I'll be writing a blog post to guide you through the process soon. Thank you!

**Closed by MohammadrezaPourreza** 2024-02-02 15:30 UTC

**Comment by alifzl** [comment] 2024-02-03 09:31
> @alifzl @ankur198 @deeteeakl @Namec999 I'm sorry for the delay in getting back to you, but I have some exciting news to share! We now support open-source LLMs, and you can easily use any model from Hugging Face with our tool. We've merged the code, and I'll be writing a blog post to guide you through the process soon. Thank you!


@MohammadrezaPourreza looking forward to check the blog post of yours in order to check how we can use and fine tune Local Custom LLMs in your great solution.

cheers.

**Comment by moltar** [comment] 2024-02-16 09:35
@MohammadrezaPourreza Have you documented or blogged the approach for custom LLM setup yet? Cheers?
